// <auto-generated />
using System;
using BataAppHR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BataAppHR.Migrations.FormDB
{
    [DbContext(typeof(FormDBContext))]
    [Migration("20210804082846_DBInit")]
    partial class DBInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BataAppHR.Models.VaksinModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EMAIL_SS")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("FLAG_AKTIF")
                        .HasColumnType("int");

                    b.Property<string>("FOTOSERTIFIKAT1")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("FOTOSERTIFIKAT2")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("HP_SS")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("JOIN_DATE")
                        .HasColumnType("date");

                    b.Property<string>("KTP")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LAMA_KERJA")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NAMA_SS")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("RESIGN_DATE")
                        .HasColumnType("date");

                    b.Property<string>("RESIGN_TXT")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SEX")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SIZE_SEPATU_UK")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SIZE_SERAGAM")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SS_CODE")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VAKSIN1")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VAKSIN2")
                        .HasColumnType("varchar(255)");

                    b.HasKey("ID")
                        .HasName("PK_SSTable");

                    b.ToTable("SSTable");
                });
#pragma warning restore 612, 618
        }
    }
}
