// <auto-generated />
using System;
using BataAppHR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BataAppHR.Migrations.FormDB
{
    [DbContext(typeof(FormDBContext))]
    [Migration("20230421041613_addedcolumnstorelist")]
    partial class addedcolumnstorelist
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BataAppHR.Models.SystemMenuModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("MENU_DESC")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MENU_LINK")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MENU_TXT")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ROLE_ID")
                        .HasColumnType("varchar(75)");

                    b.Property<int>("TAB_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID")
                        .HasName("PK_MENU_Seq");

                    b.ToTable("SystemMenuTbl");
                });

            modelBuilder.Entity("BataAppHR.Models.SystemTabModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ROLE_ID")
                        .HasColumnType("varchar(75)");

                    b.Property<string>("TAB_DESC")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TAB_TXT")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID")
                        .HasName("PK_TAB_Seq");

                    b.ToTable("SystemTabTbl");
                });

            modelBuilder.Entity("BataAppHR.Models.VaksinModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DAYS_LENGTH")
                        .HasColumnType("int");

                    b.Property<string>("EDP_CODE")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("EMAIL_SS")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EMERGENCY_ADDRESS")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("EMERGENCY_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EMERGENCY_PHONE")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FILE_MEDIC")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("FLAG_AKTIF")
                        .HasColumnType("int");

                    b.Property<string>("FOTOSERTIFIKAT1")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("FOTOSERTIFIKAT2")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("HP_SS")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("JOIN_DATE")
                        .HasColumnType("date");

                    b.Property<string>("KTP")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LAMA_KERJA")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MONTH_LENGTH")
                        .HasColumnType("int");

                    b.Property<string>("NAMA_SS")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("POSITION")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("RESIGN_DATE")
                        .HasColumnType("date");

                    b.Property<string>("RESIGN_TXT")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RESIGN_TYPE")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RESIGN_TYPE2")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SEX")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SIZE_SEPATU_UK")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SIZE_SERAGAM")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SS_CODE")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STAFF_PHOTO")
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VAKSIN1")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VAKSIN2")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("XSTORE_LOGIN")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("YEAR_LENGTH")
                        .HasColumnType("int");

                    b.HasKey("ID")
                        .HasName("PK_SSTable");

                    b.ToTable("SSTable");
                });

            modelBuilder.Entity("BataAppHR.Models.VaksinSeqModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id")
                        .HasName("PK_SSTable_Seq");

                    b.ToTable("sstable_seq");
                });

            modelBuilder.Entity("BataAppHR.Models.XstoreModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADDRESS")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CLOSE_DATE")
                        .HasColumnType("date");

                    b.Property<double>("DEPT_COMM")
                        .HasColumnType("double");

                    b.Property<decimal?>("DEPT_COMM_PERC")
                        .HasColumnType("decimal(11,2)");

                    b.Property<DateTime?>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FILE_LEASE")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FILE_OTHERS")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("FLAG_APPROVAL")
                        .HasColumnType("int");

                    b.Property<decimal?>("GROSS_VAL")
                        .HasColumnType("decimal(11,2)");

                    b.Property<string>("IS_DS")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("IS_PERC")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("IS_PERC_DEPT")
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime?>("LAST_RENOVATION_DATE")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LEASE_EXPIRED")
                        .HasColumnType("date");

                    b.Property<DateTime?>("LEASE_START")
                        .HasColumnType("date");

                    b.Property<DateTime?>("OPENING_DATE")
                        .HasColumnType("date");

                    b.Property<string>("RD_CODE")
                        .HasColumnType("varchar(10)");

                    b.Property<double>("RD_COMM")
                        .HasColumnType("double");

                    b.Property<decimal?>("RD_COMM_PERC")
                        .HasColumnType("decimal(11,2)");

                    b.Property<decimal?>("SELLING_AREA")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("SELLING_VAL")
                        .HasColumnType("decimal(11,2)");

                    b.Property<decimal?>("STOCK_AREA")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("STORAGE_VAL")
                        .HasColumnType("decimal(11,2)");

                    b.Property<string>("STORE_CONCEPT")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("STORE_IMAGE")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("STORE_IMG_BLOB")
                        .HasColumnType("MediumBlob");

                    b.Property<decimal?>("TOTAL_AREA")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("area")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("district")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("edp")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("genesis_Flag")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("inactive_flag")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("store_location")
                        .HasColumnType("varchar(75)");

                    b.HasKey("id")
                        .HasName("PK_xstore_organizations_num");

                    b.ToTable("xstore_organization");
                });

            modelBuilder.Entity("BataAppHR.Models.dbArticle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Article")
                        .HasColumnType("varchar(7)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<byte[]>("FILE_IMG")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_IMG_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(80)");

                    b.HasKey("id")
                        .HasName("PK_Article");

                    b.ToTable("dbArticle");
                });

            modelBuilder.Entity("BataAppHR.Models.dbCustomer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BANK_BRANCH")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BANK_COUNTRY")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BANK_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BANK_NUMBER")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BL_FLAG")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("COMPANY")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("COMPANY_ID")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CUST_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EDP")
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("FILE_AKTA")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_AKTA_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_KTP")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_KTP_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_NIB")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_NIB_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_NPWP")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_NPWP_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_REKENING")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_REKENING_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_SIUP")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_SIUP_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_SKT")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_SKT_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_SPPKP")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_SPPKP_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_TDP")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_TDP_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("KTP")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NPWP")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("PHONE1")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PHONE2")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("REG_DATE")
                        .HasColumnType("date");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("VA1")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VA1NOTE")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VA2")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VA2NOTE")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("address")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("city")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("discount_customer")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("isApproved")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("isApproved2")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("postal")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("province")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("store_area")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("totalstoreconfig")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK_Customer");

                    b.ToTable("dbCustomer");
                });

            modelBuilder.Entity("BataAppHR.Models.dbCustomerSeq", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id")
                        .HasName("PK_Cust_Seq");

                    b.ToTable("dbCustomer_seq");
                });

            modelBuilder.Entity("BataAppHR.Models.dbEmployee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DAYS_LENGTH")
                        .HasColumnType("int");

                    b.Property<string>("EMERGENCY_ADDRESS")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("EMERGENCY_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EMERGENCY_PHONE")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EMP_CODE")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("EMP_EMAIL")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EMP_HP")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EMP_PHOTO")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("EMP_SEPATU_SIZEUK")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EMP_SERAGAM_SIZE")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EMP_TYPE")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FILE_MEDIC")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("FILE_SERTIFIKAT1")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("FILE_SERTIFIKAT2")
                        .HasColumnType("varchar(300)");

                    b.Property<int>("FLAG_AKTIF")
                        .HasColumnType("int");

                    b.Property<string>("IS_SALES_WH")
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime?>("JOIN_DATE")
                        .HasColumnType("date");

                    b.Property<string>("LAMA_KERJA")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MONTH_LENGTH")
                        .HasColumnType("int");

                    b.Property<string>("NM_EMP")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("No_KTP")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("POSITION")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("RESIGN_DATE")
                        .HasColumnType("date");

                    b.Property<string>("RESIGN_TXT")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RESIGN_TYPE")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RESIGN_TYPE2")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SEX")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VAKSIN1")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VAKSIN2")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("YEAR_LENGTH")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK_dbEmp_Num");

                    b.ToTable("dbEmployee");
                });

            modelBuilder.Entity("BataAppHR.Models.dbNilaiSS", b =>
                {
                    b.Property<int>("ScoreId")
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EMP_TYPE")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Entry_Date")
                        .HasColumnType("date");

                    b.Property<string>("Entry_User")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FILE_SERTIFIKAT")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<int>("NILAI")
                        .HasColumnType("int");

                    b.Property<string>("NoSertifikat")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SERTIFIKAT")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("SS_CODE")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TRN_ID")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Update_Date")
                        .HasColumnType("date");

                    b.Property<string>("Update_User")
                        .HasColumnType("varchar(100)");

                    b.HasKey("ScoreId")
                        .HasName("PK_ScoreTbl");

                    b.ToTable("dbNilaiSS");
                });

            modelBuilder.Entity("BataAppHR.Models.dbNilaiSSFixed", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EMP_TYPE")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Entry_Date")
                        .HasColumnType("date");

                    b.Property<string>("Entry_User")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FILE_SERTIFIKAT")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ISPRESENT")
                        .HasColumnType("varchar(1)");

                    b.Property<int>("NILAI")
                        .HasColumnType("int");

                    b.Property<string>("NoSertifikat")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SERTIFIKAT")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("SS_CODE")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TRN_ID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Update_Date")
                        .HasColumnType("date");

                    b.Property<string>("Update_User")
                        .HasColumnType("varchar(100)");

                    b.HasKey("ScoreId")
                        .HasName("PK_ScoreTblFixed");

                    b.ToTable("dbNilaiSSFixed");
                });

            modelBuilder.Entity("BataAppHR.Models.dbOrderConfig", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("pairsarticle")
                        .HasColumnType("int");

                    b.Property<int>("pairsorder")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK_OrderConfig");

                    b.ToTable("dbOrderConfig");
                });

            modelBuilder.Entity("BataAppHR.Models.dbPaymentList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BANK")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<byte[]>("FILE_PAYMENT")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_PAYMENT_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime?>("PAYMENT_DATE")
                        .HasColumnType("datetime");

                    b.Property<string>("REF_ID")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("TOTAL_PAY")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<int>("id_customer")
                        .HasColumnType("int(10)");

                    b.Property<int>("id_order")
                        .HasColumnType("int(10)");

                    b.HasKey("id")
                        .HasName("PK_PaymentList");

                    b.ToTable("dbPaymentList");
                });

            modelBuilder.Entity("BataAppHR.Models.dbProgram", b =>
                {
                    b.Property<string>("ProgramId")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Entry_Date")
                        .HasColumnType("date");

                    b.Property<string>("Entry_User")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ProgramName")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Update_Date")
                        .HasColumnType("date");

                    b.Property<string>("Update_User")
                        .HasColumnType("varchar(100)");

                    b.HasKey("ProgramId")
                        .HasName("PK_ProgramTbl");

                    b.ToTable("dbProgram");
                });

            modelBuilder.Entity("BataAppHR.Models.dbProgramSeq", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id")
                        .HasName("PK_Program_Seq");

                    b.ToTable("dbProgram_seq");
                });

            modelBuilder.Entity("BataAppHR.Models.dbRD", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DAYS_LENGTH")
                        .HasColumnType("int");

                    b.Property<string>("EDP_CODE")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("EMERGENCY_ADDRESS")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("EMERGENCY_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EMERGENCY_PHONE")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FILE_MEDIC")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("FILE_SERTIFIKAT1")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("FILE_SERTIFIKAT2")
                        .HasColumnType("varchar(300)");

                    b.Property<int>("FLAG_AKTIF")
                        .HasColumnType("int");

                    b.Property<DateTime?>("JOIN_DATE")
                        .HasColumnType("date");

                    b.Property<string>("LAMA_KERJA")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MONTH_LENGTH")
                        .HasColumnType("int");

                    b.Property<string>("NM_RD")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("No_KTP")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RD_CODE")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RD_EMAIL")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RD_HP")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RD_PHOTO")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("RD_SEPATU_SIZEUK")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RD_SERAGAM_SIZE")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("RESIGN_DATE")
                        .HasColumnType("date");

                    b.Property<string>("RESIGN_TXT")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RESIGN_TYPE")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RESIGN_TYPE2")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SEX")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VAKSIN1")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VAKSIN2")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("YEAR_LENGTH")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK_RD_num");

                    b.ToTable("dbRD");
                });

            modelBuilder.Entity("BataAppHR.Models.dbRDSeq", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id")
                        .HasName("PK_RD_Seq");

                    b.ToTable("dbRDSeq");
                });

            modelBuilder.Entity("BataAppHR.Models.dbRekapTraining", b =>
                {
                    b.Property<string>("TRN_ID")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("EDP")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Entry_Date")
                        .HasColumnType("date");

                    b.Property<string>("Entry_User")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<decimal?>("Hours")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("NoParticipant")
                        .HasColumnType("int");

                    b.Property<string>("Participant")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Periode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Program")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProgramTxt")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TotalHours")
                        .HasColumnType("int");

                    b.Property<string>("Trainer")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Update_Date")
                        .HasColumnType("date");

                    b.Property<string>("Update_User")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Week")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("idTrainer")
                        .HasColumnType("varchar(255)");

                    b.HasKey("TRN_ID")
                        .HasName("PK_RekapTrainingTbl");

                    b.ToTable("dbRekapTraining");
                });

            modelBuilder.Entity("BataAppHR.Models.dbRekapTrainingSeq", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id")
                        .HasName("PK_RekapTraining_Seq");

                    b.ToTable("dbRekapTraining_seq");
                });

            modelBuilder.Entity("BataAppHR.Models.dbSalesOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("APPROVAL_1")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("APPROVAL_2")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("APPROVAL_AR")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("EMAIL")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EMP_CODE")
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("FLAG_SENT")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("INV_DISC")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("INV_DISC_AMT")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("IS_DISC_PERC")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("ORDER_DATE")
                        .HasColumnType("datetime");

                    b.Property<string>("SHIPPING_ADDRESS")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STATUS")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("TOTAL_ORDER")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("TOTAL_QTY")
                        .HasColumnType("int(10)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("id_customer")
                        .HasColumnType("int(10)");

                    b.Property<string>("picking_no")
                        .HasColumnType("varchar(20)");

                    b.HasKey("id")
                        .HasName("PK_SalesOrder");

                    b.ToTable("dbSalesOrder");
                });

            modelBuilder.Entity("BataAppHR.Models.dbSalesOrderDtl", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Size_1")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_10")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_11")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_12")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_13")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_2")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_3")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_4")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_5")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_6")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_7")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_8")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_9")
                        .HasColumnType("int(10)");

                    b.Property<string>("article")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("disc")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("disc_amt")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("final_price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("id_order")
                        .HasColumnType("int(10)");

                    b.Property<string>("is_disc_perc")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("qty")
                        .HasColumnType("int(10)");

                    b.Property<string>("size")
                        .HasColumnType("varchar(10)");

                    b.HasKey("id")
                        .HasName("PK_SalesOrderDtl");

                    b.ToTable("dbSalesOrderDtl");
                });

            modelBuilder.Entity("BataAppHR.Models.dbSalesOrderDtlCredit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Size_1")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_10")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_11")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_12")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_13")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_2")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_3")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_4")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_5")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_6")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_7")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_8")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_9")
                        .HasColumnType("int(10)");

                    b.Property<string>("article")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("disc")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("disc_amt")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("final_price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("id_order")
                        .HasColumnType("int(10)");

                    b.Property<string>("is_disc_perc")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("picking_no")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("qty")
                        .HasColumnType("int(10)");

                    b.Property<string>("size")
                        .HasColumnType("varchar(10)");

                    b.HasKey("id")
                        .HasName("PK_SalesOrderDtlCredit");

                    b.ToTable("SalesOrderDtlCreditTbl");
                });

            modelBuilder.Entity("BataAppHR.Models.dbSalesOrderDtlTemp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Size_1")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_10")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_11")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_12")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_13")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_2")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_3")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_4")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_5")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_6")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_7")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_8")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_9")
                        .HasColumnType("int(10)");

                    b.Property<string>("article")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("disc")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("disc_amt")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("final_price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("id_order")
                        .HasColumnType("int(10)");

                    b.Property<string>("is_disc_perc")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("qty")
                        .HasColumnType("int(10)");

                    b.Property<string>("size")
                        .HasColumnType("varchar(10)");

                    b.HasKey("id")
                        .HasName("PK_SalesOrderDtlTemp");

                    b.ToTable("dbSalesOrderDtlTemp");
                });

            modelBuilder.Entity("BataAppHR.Models.dbSalesOrderTemp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("APPROVAL_1")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("APPROVAL_2")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("APPROVAL_AR")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("EMAIL")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EMP_CODE")
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("FLAG_SENT")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("INV_DISC")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("INV_DISC_AMT")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("IS_DISC_PERC")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("ORDER_DATE")
                        .HasColumnType("datetime");

                    b.Property<string>("SHIPPING_ADDRESS")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STATUS")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("TOTAL_ORDER")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("TOTAL_QTY")
                        .HasColumnType("int(10)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("id_customer")
                        .HasColumnType("int(10)");

                    b.HasKey("id")
                        .HasName("PK_SalesOrderTemp");

                    b.ToTable("dbSalesOrderTemp");
                });

            modelBuilder.Entity("BataAppHR.Models.dbSalesWholeSale", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EMP_CODE")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(80)");

                    b.HasKey("id")
                        .HasName("PK_SalesWhole");

                    b.ToTable("dbSalesWholeSale");
                });

            modelBuilder.Entity("BataAppHR.Models.dbSliderImg", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FILE_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<byte[]>("IMG_DESC")
                        .HasColumnType("MediumBlob");

                    b.Property<byte[]>("SLIDE_IMG_BLOB")
                        .HasColumnType("longblob");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID")
                        .HasName("PK_SliderImg");

                    b.ToTable("dbSliderImg");
                });

            modelBuilder.Entity("BataAppHR.Models.dbTrainer", b =>
                {
                    b.Property<string>("idTrainer")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Entry_Date")
                        .HasColumnType("date");

                    b.Property<string>("Entry_User")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("HP")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NmShort")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NmTrainer")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Update_Date")
                        .HasColumnType("date");

                    b.Property<string>("Update_User")
                        .HasColumnType("varchar(100)");

                    b.HasKey("idTrainer")
                        .HasName("PK_TrainerTbl");

                    b.ToTable("dbTrainer");
                });

            modelBuilder.Entity("BataAppHR.Models.dbTrainerList", b =>
                {
                    b.Property<int>("idTrainerList")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("idFormRekap")
                        .HasColumnType("int");

                    b.Property<string>("idTrainer")
                        .HasColumnType("varchar(50)");

                    b.HasKey("idTrainerList")
                        .HasName("PK_idTrainerList");

                    b.ToTable("dbTrainerList");
                });

            modelBuilder.Entity("BataAppHR.Models.dbTrainerSeq", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id")
                        .HasName("PK_Trainer_Seq");

                    b.ToTable("dbTrainer_seq");
                });

            modelBuilder.Entity("BataAppHR.Models.dbrekapTrainingfixed", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Batch")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("Days")
                        .HasColumnType("DECIMAL(6,2)");

                    b.Property<string>("EDP")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Entry_Date")
                        .HasColumnType("date");

                    b.Property<string>("Entry_User")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<decimal?>("Hours")
                        .HasColumnType("DECIMAL(6,2)");

                    b.Property<int?>("NoParticipant")
                        .HasColumnType("int");

                    b.Property<string>("Participant")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Periode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Program")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProgramTxt")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TRN_ID")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("TotalHours")
                        .HasColumnType("DECIMAL(6,2)");

                    b.Property<string>("Trainer")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("TrainingDays")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Update_Date")
                        .HasColumnType("date");

                    b.Property<string>("Update_User")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Week")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("idTrainer")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id")
                        .HasName("PK_RekapTrainingTblFixed");

                    b.ToTable("dbRekapTrainingFixed");
                });

            modelBuilder.Entity("BataAppHR.Models.dbsalescreditlog", b =>
                {
                    b.Property<string>("edp")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("invno")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("isused")
                        .HasColumnType("varchar(1)");

                    b.Property<decimal?>("valuecredit")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("edp", "invno");

                    b.ToTable("dbSalesCreditLog");
                });

            modelBuilder.Entity("BataAppHR.Models.dbsalesorderpicking", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id")
                        .HasName("PK_salesorderpicking");

                    b.ToTable("dbsalesorderpicking");
                });

            modelBuilder.Entity("BataAppHR.Models.dbsalesorderpickingref", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id")
                        .HasName("PK_salesorderpickingref");

                    b.ToTable("dbsalesorderpickingref");
                });

            modelBuilder.Entity("OnPOS.Models.dbCompanySeq", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id")
                        .HasName("PK_Company_Seq");

                    b.ToTable("dbCompany_seq");
                });

            modelBuilder.Entity("OnPOS.Models.dbStoreList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("COMPANY_ID")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("datetime");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_PHOTO")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_PHOTO_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("STORE_ADDRESS")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_BANK_BRANCH")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_BANK_COUNTRY")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_BANK_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_BANK_NUMBER")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_BL_FLAG")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("STORE_CITY")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_EMAIL")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_MANAGER_EMAIL")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_MANAGER_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_MANAGER_PHONE")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_POSTAL")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_PROVINCE")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("STORE_REG_DATE")
                        .HasColumnType("date");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id")
                        .HasName("PK_StoreList");

                    b.ToTable("dbStoreList");
                });
#pragma warning restore 612, 618
        }
    }
}
