// <auto-generated />
using System;
using BataAppHR.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BataAppHR.Migrations.FormDB
{
    [DbContext(typeof(FormDBContext))]
    [Migration("20240609034156_removingtblpart2")]
    partial class removingtblpart2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BataAppHR.Models.SystemMenuModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("MENU_DESC")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MENU_LINK")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("MENU_TXT")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ROLE_ID")
                        .HasColumnType("varchar(75)");

                    b.Property<int>("TAB_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID")
                        .HasName("PK_MENU_Seq");

                    b.ToTable("SystemMenuTbl");
                });

            modelBuilder.Entity("BataAppHR.Models.SystemTabModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ROLE_ID")
                        .HasColumnType("varchar(75)");

                    b.Property<string>("TAB_DESC")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TAB_TXT")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID")
                        .HasName("PK_TAB_Seq");

                    b.ToTable("SystemTabTbl");
                });

            modelBuilder.Entity("BataAppHR.Models.dbArticle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Article")
                        .HasColumnType("varchar(7)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<byte[]>("FILE_IMG")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_IMG_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(80)");

                    b.HasKey("id")
                        .HasName("PK_Article");

                    b.ToTable("dbArticle");
                });

            modelBuilder.Entity("BataAppHR.Models.dbCustomer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BANK_BRANCH")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BANK_COUNTRY")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BANK_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BANK_NUMBER")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BL_FLAG")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("COMPANY")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("COMPANY_ID")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("CUST_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EDP")
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<byte[]>("FILE_AKTA")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_AKTA_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_KTP")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_KTP_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_NIB")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_NIB_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_NPWP")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_NPWP_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_REKENING")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_REKENING_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_SIUP")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_SIUP_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_SKT")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_SKT_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_SPPKP")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_SPPKP_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_TDP")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_TDP_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("KTP")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NPWP")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("PHONE1")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PHONE2")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("REG_DATE")
                        .HasColumnType("date");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("VA1")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VA1NOTE")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VA2")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("VA2NOTE")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("address")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("city")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("discount_customer")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("isApproved")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("isApproved2")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("postal")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("province")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("store_area")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("totalstoreconfig")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK_Customer");

                    b.ToTable("dbCustomer");
                });

            modelBuilder.Entity("BataAppHR.Models.dbCustomerSeq", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id")
                        .HasName("PK_Cust_Seq");

                    b.ToTable("dbCustomer_seq");
                });

            modelBuilder.Entity("BataAppHR.Models.dbNilaiSS", b =>
                {
                    b.Property<int>("ScoreId")
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EMP_TYPE")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Entry_Date")
                        .HasColumnType("date");

                    b.Property<string>("Entry_User")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FILE_SERTIFIKAT")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<int>("NILAI")
                        .HasColumnType("int");

                    b.Property<string>("NoSertifikat")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SERTIFIKAT")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("SS_CODE")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TRN_ID")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Update_Date")
                        .HasColumnType("date");

                    b.Property<string>("Update_User")
                        .HasColumnType("varchar(100)");

                    b.HasKey("ScoreId")
                        .HasName("PK_ScoreTbl");

                    b.ToTable("dbNilaiSS");
                });

            modelBuilder.Entity("BataAppHR.Models.dbNilaiSSFixed", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EMP_TYPE")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Entry_Date")
                        .HasColumnType("date");

                    b.Property<string>("Entry_User")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FILE_SERTIFIKAT")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ISPRESENT")
                        .HasColumnType("varchar(1)");

                    b.Property<int>("NILAI")
                        .HasColumnType("int");

                    b.Property<string>("NoSertifikat")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SERTIFIKAT")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("SS_CODE")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TRN_ID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Update_Date")
                        .HasColumnType("date");

                    b.Property<string>("Update_User")
                        .HasColumnType("varchar(100)");

                    b.HasKey("ScoreId")
                        .HasName("PK_ScoreTblFixed");

                    b.ToTable("dbNilaiSSFixed");
                });

            modelBuilder.Entity("BataAppHR.Models.dbOrderConfig", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("pairsarticle")
                        .HasColumnType("int");

                    b.Property<int>("pairsorder")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK_OrderConfig");

                    b.ToTable("dbOrderConfig");
                });

            modelBuilder.Entity("BataAppHR.Models.dbPaymentList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BANK")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<byte[]>("FILE_PAYMENT")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_PAYMENT_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime?>("PAYMENT_DATE")
                        .HasColumnType("datetime");

                    b.Property<string>("REF_ID")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("TOTAL_PAY")
                        .HasColumnType("decimal(15,2)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<int>("id_customer")
                        .HasColumnType("int(10)");

                    b.Property<int>("id_order")
                        .HasColumnType("int(10)");

                    b.HasKey("id")
                        .HasName("PK_PaymentList");

                    b.ToTable("dbPaymentList");
                });

            modelBuilder.Entity("BataAppHR.Models.dbProgram", b =>
                {
                    b.Property<string>("ProgramId")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Entry_Date")
                        .HasColumnType("date");

                    b.Property<string>("Entry_User")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ProgramName")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Update_Date")
                        .HasColumnType("date");

                    b.Property<string>("Update_User")
                        .HasColumnType("varchar(100)");

                    b.HasKey("ProgramId")
                        .HasName("PK_ProgramTbl");

                    b.ToTable("dbProgram");
                });

            modelBuilder.Entity("BataAppHR.Models.dbProgramSeq", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id")
                        .HasName("PK_Program_Seq");

                    b.ToTable("dbProgram_seq");
                });

            modelBuilder.Entity("BataAppHR.Models.dbRekapTraining", b =>
                {
                    b.Property<string>("TRN_ID")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("EDP")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Entry_Date")
                        .HasColumnType("date");

                    b.Property<string>("Entry_User")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<decimal?>("Hours")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int>("NoParticipant")
                        .HasColumnType("int");

                    b.Property<string>("Participant")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Periode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Program")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProgramTxt")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TotalHours")
                        .HasColumnType("int");

                    b.Property<string>("Trainer")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Update_Date")
                        .HasColumnType("date");

                    b.Property<string>("Update_User")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Week")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("idTrainer")
                        .HasColumnType("varchar(255)");

                    b.HasKey("TRN_ID")
                        .HasName("PK_RekapTrainingTbl");

                    b.ToTable("dbRekapTraining");
                });

            modelBuilder.Entity("BataAppHR.Models.dbRekapTrainingSeq", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id")
                        .HasName("PK_RekapTraining_Seq");

                    b.ToTable("dbRekapTraining_seq");
                });

            modelBuilder.Entity("BataAppHR.Models.dbSalesOrder", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("APPROVAL_1")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("APPROVAL_2")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("APPROVAL_AR")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("EMAIL")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EMP_CODE")
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("FLAG_SENT")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("INV_DISC")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("INV_DISC_AMT")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("IS_DISC_PERC")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("ORDER_DATE")
                        .HasColumnType("datetime");

                    b.Property<string>("SHIPPING_ADDRESS")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STATUS")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("TOTAL_ORDER")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("TOTAL_QTY")
                        .HasColumnType("int(10)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("id_customer")
                        .HasColumnType("int(10)");

                    b.Property<string>("picking_no")
                        .HasColumnType("varchar(20)");

                    b.HasKey("id")
                        .HasName("PK_SalesOrder");

                    b.ToTable("dbSalesOrder");
                });

            modelBuilder.Entity("BataAppHR.Models.dbSalesOrderDtl", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Size_1")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_10")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_11")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_12")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_13")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_2")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_3")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_4")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_5")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_6")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_7")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_8")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_9")
                        .HasColumnType("int(10)");

                    b.Property<string>("article")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("disc")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("disc_amt")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("final_price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("id_order")
                        .HasColumnType("int(10)");

                    b.Property<string>("is_disc_perc")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("qty")
                        .HasColumnType("int(10)");

                    b.Property<string>("size")
                        .HasColumnType("varchar(10)");

                    b.HasKey("id")
                        .HasName("PK_SalesOrderDtl");

                    b.ToTable("dbSalesOrderDtl");
                });

            modelBuilder.Entity("BataAppHR.Models.dbSalesOrderDtlCredit", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Size_1")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_10")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_11")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_12")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_13")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_2")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_3")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_4")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_5")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_6")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_7")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_8")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_9")
                        .HasColumnType("int(10)");

                    b.Property<string>("article")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("disc")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("disc_amt")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("final_price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("id_order")
                        .HasColumnType("int(10)");

                    b.Property<string>("is_disc_perc")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("picking_no")
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("qty")
                        .HasColumnType("int(10)");

                    b.Property<string>("size")
                        .HasColumnType("varchar(10)");

                    b.HasKey("id")
                        .HasName("PK_SalesOrderDtlCredit");

                    b.ToTable("SalesOrderDtlCreditTbl");
                });

            modelBuilder.Entity("BataAppHR.Models.dbSalesOrderDtlTemp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Size_1")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_10")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_11")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_12")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_13")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_2")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_3")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_4")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_5")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_6")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_7")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_8")
                        .HasColumnType("int(10)");

                    b.Property<int>("Size_9")
                        .HasColumnType("int(10)");

                    b.Property<string>("article")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("disc")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("disc_amt")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("final_price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("id_order")
                        .HasColumnType("int(10)");

                    b.Property<string>("is_disc_perc")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("price")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("qty")
                        .HasColumnType("int(10)");

                    b.Property<string>("size")
                        .HasColumnType("varchar(10)");

                    b.HasKey("id")
                        .HasName("PK_SalesOrderDtlTemp");

                    b.ToTable("dbSalesOrderDtlTemp");
                });

            modelBuilder.Entity("BataAppHR.Models.dbSalesOrderTemp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("APPROVAL_1")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("APPROVAL_2")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("APPROVAL_AR")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("EMAIL")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EMP_CODE")
                        .HasColumnType("varchar(25)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("FLAG_SENT")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("INV_DISC")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("INV_DISC_AMT")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("IS_DISC_PERC")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime?>("ORDER_DATE")
                        .HasColumnType("datetime");

                    b.Property<string>("SHIPPING_ADDRESS")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STATUS")
                        .HasColumnType("varchar(10)");

                    b.Property<decimal?>("TOTAL_ORDER")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("TOTAL_QTY")
                        .HasColumnType("int(10)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<int?>("id_customer")
                        .HasColumnType("int(10)");

                    b.HasKey("id")
                        .HasName("PK_SalesOrderTemp");

                    b.ToTable("dbSalesOrderTemp");
                });

            modelBuilder.Entity("BataAppHR.Models.dbSalesWholeSale", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EMP_CODE")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(80)");

                    b.HasKey("id")
                        .HasName("PK_SalesWhole");

                    b.ToTable("dbSalesWholeSale");
                });

            modelBuilder.Entity("BataAppHR.Models.dbSliderImg", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FILE_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<byte[]>("IMG_DESC")
                        .HasColumnType("MediumBlob");

                    b.Property<byte[]>("SLIDE_IMG_BLOB")
                        .HasColumnType("longblob");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("ID")
                        .HasName("PK_SliderImg");

                    b.ToTable("dbSliderImg");
                });

            modelBuilder.Entity("BataAppHR.Models.dbrekapTrainingfixed", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Batch")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("Days")
                        .HasColumnType("DECIMAL(6,2)");

                    b.Property<string>("EDP")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Entry_Date")
                        .HasColumnType("date");

                    b.Property<string>("Entry_User")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<decimal?>("Hours")
                        .HasColumnType("DECIMAL(6,2)");

                    b.Property<int?>("NoParticipant")
                        .HasColumnType("int");

                    b.Property<string>("Participant")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Periode")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Program")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProgramTxt")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TRN_ID")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("TotalHours")
                        .HasColumnType("DECIMAL(6,2)");

                    b.Property<string>("Trainer")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("TrainingDays")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("Update_Date")
                        .HasColumnType("date");

                    b.Property<string>("Update_User")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Week")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("idTrainer")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id")
                        .HasName("PK_RekapTrainingTblFixed");

                    b.ToTable("dbRekapTrainingFixed");
                });

            modelBuilder.Entity("BataAppHR.Models.dbsalescreditlog", b =>
                {
                    b.Property<string>("edp")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("invno")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("isused")
                        .HasColumnType("varchar(1)");

                    b.Property<decimal?>("valuecredit")
                        .HasColumnType("decimal(15,2)");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("edp")
                        .HasName("PK_Creditlogs");

                    b.ToTable("dbSalesCreditLog");
                });

            modelBuilder.Entity("BataAppHR.Models.dbsalesorderpicking", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id")
                        .HasName("PK_salesorderpicking");

                    b.ToTable("dbsalesorderpicking");
                });

            modelBuilder.Entity("BataAppHR.Models.dbsalesorderpickingref", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id")
                        .HasName("PK_salesorderpickingref");

                    b.ToTable("dbsalesorderpickingref");
                });

            modelBuilder.Entity("OnPOS.Models.dbCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("COMPANY_ID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Category")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("description")
                        .HasColumnType("varchar(100)");

                    b.HasKey("id")
                        .HasName("PK_Category");

                    b.ToTable("dbCategory");
                });

            modelBuilder.Entity("OnPOS.Models.dbCompanySeq", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id")
                        .HasName("PK_Company_Seq");

                    b.ToTable("dbCompany_seq");
                });

            modelBuilder.Entity("OnPOS.Models.dbItemMaster", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("COMPANY_ID")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("brand")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("category")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("color")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("itemdescription")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("itemid")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("price1")
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("price2")
                        .HasColumnType("decimal(19,2)");

                    b.Property<decimal>("price3")
                        .HasColumnType("decimal(19,2)");

                    b.Property<string>("size")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("subcategory")
                        .HasColumnType("varchar(50)");

                    b.HasKey("id")
                        .HasName("PK_ItemMaster");

                    b.ToTable("dbItemMaster");
                });

            modelBuilder.Entity("OnPOS.Models.dbItemStore", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("COMPANY_ID")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("STORE_NAME")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("itemid")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("itemidint")
                        .HasColumnType("int");

                    b.Property<int>("storeid")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK_ItemStore");

                    b.ToTable("dbItemStore");
                });

            modelBuilder.Entity("OnPOS.Models.dbStoreList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("COMPANY_ID")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("datetime");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(255)");

                    b.Property<byte[]>("FILE_PHOTO")
                        .HasColumnType("MediumBlob");

                    b.Property<string>("FILE_PHOTO_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("STORE_ADDRESS")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_BANK_BRANCH")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_BANK_COUNTRY")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_BANK_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_BANK_NUMBER")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_BL_FLAG")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("STORE_CITY")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_EMAIL")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_MANAGER_EMAIL")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_MANAGER_KTP")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_MANAGER_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_MANAGER_PHONE")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_NAME")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_POSTAL")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("STORE_PROVINCE")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("STORE_REG_DATE")
                        .HasColumnType("date");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("datetime");

                    b.Property<string>("UPDATE_USER")
                        .HasColumnType("varchar(255)");

                    b.HasKey("id")
                        .HasName("PK_StoreList");

                    b.ToTable("dbStoreList");
                });

            modelBuilder.Entity("OnPOS.Models.dbSubCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("COMPANY_ID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ENTRY_DATE")
                        .HasColumnType("date");

                    b.Property<string>("ENTRY_USER")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FLAG_AKTIF")
                        .HasColumnType("varchar(1)");

                    b.Property<string>("SubCategory")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UPDATE_DATE")
                        .HasColumnType("date");

                    b.Property<string>("UPDATE_USER")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("description")
                        .HasColumnType("varchar(100)");

                    b.HasKey("id")
                        .HasName("PK_SubCategory");

                    b.ToTable("dbSubCategory");
                });
#pragma warning restore 612, 618
        }
    }
}
